package br.com.diogo.compile.lexico;

public enum enumTokens {

  

    TK_IDENTIFIER,
    TK_NUMBER,
    TK_OPERATOR,
    TK_PONCTUATION ,
    TK_ASSIGN ,

    TK_RESERVED_WORD_IF,
    TK_RESERVED_WORD_ELSE,
    TK_RESERVED_WORD_WHILE,
    TK_RESERVED_WORD_FOR,
    TK_RESERVED_WORD_DO,
    TK_RESERVED_WORD_STRING,
    TK_RESERVED_WORD_NULL,
    TK_RESERVED_WORD_INT,
    TK_RESERVED_WORD_FLOAT,
    TK_RESERVED_WORD_DOUBLE,
    TK_RESERVED_WORD_BOOLEAN,
    TK_RESERVED_WORD_TRUE,
    TK_RESERVED_WORD_FALSE,
    TK_RESERVED_WORD_VOID,
    TK_RESERVED_WORD_RETURN,
    TK_RESERVED_WORD_MAIN,
    
    TK_PONTO_VIRGULA,
    TK_VIRGULA,
    TK_INTERROGACAO,
    TK_PONTO,
    TK_DOIS_PONTOS,
    
    TK_PARENTESES,
    TK_COLCHETES,
    TK_CHAVES,

    TK_OPERADOR_SOMA,
    TK_OPERADOR_SUBTRACAO,
    TK_OPERADOR_MULTIPLICACAO,
    TK_OPERADOR_DIVISAO,
    TK_OPERADOR_PORCENTAGEM,


  
}
